sudo: required
services:
  - docker

script:
  - docker build -t razorwebs/node .
  - docker images razorwebs/node

before_deploy:
  - docker login -u razorwebs -p Systemfiles!3

deploy:
  provider: script
  script: docker push razorwebs/node
  on:
    branch: master
